---
title: "Untitled"
author: "Shelly Trigg"
date: "10/3/2020"
output: html_document
---

load libraries
```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(tidyr)
```


```{r}

#replaced the ", " with "_" with sed and awk

#sed 's/, /_/g' Mcap_cov_perc_group_3x.csv | awk -F"," '{OFS=FS=","}{print $1,$2,$3,$4,$5,$6,$7,$9}' > Mcap_cov_perc_group_3x_underscore.csv

#sed 's/, /_/g' Pact_cov_perc_group_3x.csv | awk -F"," '{OFS=FS=","}{print $1,$2,$3,$4,$5,$6,$7,$9}' > Pact_cov_perc_group_3x_underscore.csv

Pact_cov_perc <- data.frame(fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200910/Pact_cov_perc.txt", sep = ",", stringsAsFactors = F)) 

Mcap_cov_perc <- data.frame(fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200910/Mcap_cov_perc.txt", sep = ",", stringsAsFactors = F)) 

```


Filter for loci with 5x 
```{r}
Pact_cov_perc <- Pact_cov_perc[which(Pact_cov_perc$reads >=5),]

Mcap_cov_perc <- Mcap_cov_perc[which(Mcap_cov_perc$reads >=5),]


```


Summarize data (total loci for each group and method)
```{r}
Pact_meth_stats <- Pact_cov_perc  %>% group_by(loci,method) %>% summarise(medn_meth = median(perc_meth),indivd = n())

#filter for loci with coverage in all three samples/method
Pact_meth_stats <- Pact_meth_stats[which(Pact_meth_stats$indivd==3),]

# specify % meth interval bin labels
meth_tags <- c("[0-10%]","[10-20%]", "[20-30%]", "[30-40%]", "[40-50%]", "[50-60%]", "[60-70%]", "[70-80%]","[80-90%]", "[90-100%]")

Pact_meth_stats_tag <- as_tibble(Pact_meth_stats) %>% mutate(meth_tag = case_when(medn_meth < 10 ~ meth_tags[1],medn_meth >= 10 & medn_meth < 20 ~ meth_tags[2],medn_meth >= 20 & medn_meth < 30 ~ meth_tags[3],medn_meth >= 30 & medn_meth < 40 ~ meth_tags[4],medn_meth >= 40 & medn_meth < 50 ~ meth_tags[5], medn_meth >= 50 & medn_meth < 60 ~ meth_tags[6], medn_meth >= 60 & medn_meth < 70 ~ meth_tags[7], medn_meth >= 70 & medn_meth < 80 ~ meth_tags[8], medn_meth >= 80 & medn_meth < 90 ~ meth_tags[9], medn_meth >= 90 & medn_meth <= 100 ~ meth_tags[10]))

Pact_cov_perc_group <- Pact_meth_stats_tag %>% group_by(loci) %>% mutate(group = toString(method))

uniqMethod.FUN <- function(x){paste(sort(unique(unlist(strsplit(x, split =", "), use.names = F))), collapse = ", ")}

Pact_cov_perc_group$group_simp <- sapply(Pact_cov_perc_group$group, uniqMethod.FUN, USE.NAMES = F)

Pact_cov_perc_STACKED <- data.frame(Pact_cov_perc_group) %>% group_by(group_simp, method,meth_tag) %>% summarise(count_meth=n()) %>% 
  mutate(perc_CpG=count_meth/sum(count_meth), cumsum = cumsum(perc_CpG), label = ifelse(meth_tag=="[90-100%]",paste0("N=", sum(count_meth)),""))

#order group_simp

Pact_cov_perc_STACKED$group_simp <- factor(
Pact_cov_perc_STACKED$group_simp, levels = c("MBD", "RRBS", "WGBS", "MBD, RRBS","MBD, WGBS", "RRBS, WGBS", "MBD, RRBS, WGBS"))

#exclude loci with less than 5 reads in "cov_tag" column
#group by method, methylation level tag ("meth_tag"), and the overlap category ("group_simp")
#total the loci for each grouping ("count")
# calculate the percentage of CpGs within each grouping ("perc_CpG")
# calculate the total number of CpGs within each methods grouping ("group_simp")
# create a label column containing only the total number of CpGs for the "group_simp"
Mcap_meth_stats <- Mcap_cov_perc  %>% group_by(loci,method) %>% summarise(medn_meth = median(perc_meth),indivd = n())

#filter for loci with coverage in all three samples/method
Mcap_meth_stats <- Mcap_meth_stats[which(Mcap_meth_stats$indivd==3),]

# specify % meth interval bin labels
meth_tags <- c("[0-10%]","[10-20%]", "[20-30%]", "[30-40%]", "[40-50%]", "[50-60%]", "[60-70%]", "[70-80%]","[80-90%]", "[90-100%]")

Mcap_meth_stats_tag <- as_tibble(Mcap_meth_stats) %>% mutate(meth_tag = case_when(medn_meth < 10 ~ meth_tags[1],medn_meth >= 10 & medn_meth < 20 ~ meth_tags[2],medn_meth >= 20 & medn_meth < 30 ~ meth_tags[3],medn_meth >= 30 & medn_meth < 40 ~ meth_tags[4],medn_meth >= 40 & medn_meth < 50 ~ meth_tags[5], medn_meth >= 50 & medn_meth < 60 ~ meth_tags[6], medn_meth >= 60 & medn_meth < 70 ~ meth_tags[7], medn_meth >= 70 & medn_meth < 80 ~ meth_tags[8], medn_meth >= 80 & medn_meth < 90 ~ meth_tags[9], medn_meth >= 90 & medn_meth <= 100 ~ meth_tags[10]))

Mcap_cov_perc_group <- Mcap_meth_stats_tag %>% group_by(loci) %>% mutate(group = toString(method))

uniqMethod.FUN <- function(x){paste(sort(unique(unlist(strsplit(x, split =", "), use.names = F))), collapse = ", ")}

Mcap_cov_perc_group$group_simp <- sapply(Mcap_cov_perc_group$group, uniqMethod.FUN, USE.NAMES = F)

Mcap_cov_perc_STACKED <- data.frame(Mcap_cov_perc_group) %>% group_by(group_simp, method,meth_tag) %>% summarise(count_meth=n()) %>% 
  mutate(perc_CpG=count_meth/sum(count_meth), cumsum = cumsum(perc_CpG), label = ifelse(meth_tag=="[90-100%]",paste0("N=", sum(count_meth)),""))

Mcap_cov_perc_STACKED$group_simp <- factor(
Mcap_cov_perc_STACKED$group_simp, levels = c("MBD", "RRBS", "WGBS", "MBD, RRBS","MBD, WGBS", "RRBS, WGBS", "MBD, RRBS, WGBS"))


```


plot data

```{r}
d <- ggplot(Pact_cov_perc_STACKED,aes(x = method, y = perc_CpG*100, fill = as.factor(method), alpha = meth_tag, group = method )) + geom_bar(stat = "identity",position = "fill", color = "black") + theme_bw() + theme(axis.text.x = element_text(size = 7, angle = 60, hjust = 1), axis.title = element_text(size = 12, face = "bold")) + scale_fill_manual(values =c("#E6550D","#756BB1","#31A354"))  + scale_y_continuous(expand = expansion(mult = c(0, 0.1)),labels=scales::percent) + scale_alpha_manual(values=c(seq(0.1,1, length.out = 10)))+ labs(x = "method", y = "% CpGs",fill = "method", alpha = "% methylation") +  geom_text(aes(y=cumsum, label=label), vjust=-0.5, size = 2.5) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank()) + facet_grid(~ group_simp, space="free_x", scales="free_x") + theme(strip.background = element_rect(fill=NA,colour="grey50"),panel.spacing=unit(0,"cm"))
#dev.off()

#RRBS zoomed

Pact_cov_perc_STACKED_rrbsZOOM <- Pact_cov_perc_STACKED[which(Pact_cov_perc_STACKED$meth_tag!="[0-10%]" & Pact_cov_perc_STACKED$meth_tag!="[10-20%]" & Pact_cov_perc_STACKED$method=="RRBS" & Pact_cov_perc_STACKED$group_simp!="MBD, RRBS" & Pact_cov_perc_STACKED$group_simp!="MBD, WGBS"),]

Pact_cov_perc_STACKED_rrbsZOOM <- data.frame(Pact_cov_perc_STACKED_rrbsZOOM) %>% group_by(group_simp, method) %>%  mutate(label = ifelse(meth_tag=="[90-100%]",paste0("N=", sum(count_meth)),""), cumsum = cumsum(perc_CpG)*100)

e <- ggplot(Pact_cov_perc_STACKED_rrbsZOOM,aes(x = method, y = perc_CpG*100, fill = as.factor(method), alpha = meth_tag, group = method )) + geom_bar(stat = "identity",position = "stack", color = "black") + theme_bw() + theme(axis.text.x = element_text(size = 7, angle = 60, hjust = 1), axis.title = element_text(size = 12, face = "bold")) + scale_fill_manual(values =c("#756BB1"))  + scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + scale_alpha_manual(values=c(seq(0.3,1, length.out = 8)))+ labs(x = "method", y = "% CpGs",fill = "method", alpha = "% methylation") + guides(fill=guide_legend(reverse=T)) + geom_text(aes(y=cumsum * 1.05, label=label), size = 2.5) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank()) + facet_wrap(~group_simp, scale="free") + theme(strip.background = element_rect(fill=NA,colour="grey50"))

#wgbs zoomed
Pact_cov_perc_STACKED_wgbsZOOM <- Pact_cov_perc_STACKED[which(Pact_cov_perc_STACKED$meth_tag!="[0-10%]" & Pact_cov_perc_STACKED$meth_tag!="[10-20%]" & Pact_cov_perc_STACKED$method=="WGBS" & Pact_cov_perc_STACKED$group_simp!="MBD, RRBS" & Pact_cov_perc_STACKED$group_simp!="MBD, WGBS"),]

Pact_cov_perc_STACKED_wgbsZOOM <- data.frame(Pact_cov_perc_STACKED_wgbsZOOM) %>% group_by(group_simp, method) %>%  mutate(label = ifelse(meth_tag=="[90-100%]",paste0("N=", sum(count_meth)),""), cumsum = cumsum(perc_CpG)*100)



f <- ggplot(Pact_cov_perc_STACKED_wgbsZOOM,aes(x = method, y = perc_CpG*100, fill = as.factor(method), alpha = meth_tag, group = method )) + geom_bar(stat = "identity",position = "stack", color = "black") + theme_bw() + theme(axis.text.x = element_text(size = 7, angle = 60, hjust = 1), axis.title = element_text(size = 12, face = "bold")) + scale_fill_manual(values =c("#31A354"))  + scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + scale_alpha_manual(values=c(seq(0.3,1, length.out = 8)))+ labs(x = "method", y = "% CpGs",fill = "method", alpha = "% methylation") + guides(fill=guide_legend(reverse=T)) + geom_text(aes(y=cumsum * 1.05, label=label), size = 2.5) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank()) + facet_wrap(~group_simp, scale="free") + theme(strip.background = element_rect(fill=NA,colour="grey50"))



g <- ggplot(Mcap_cov_perc_STACKED,aes(x = method, y = perc_CpG*100, fill = as.factor(method), alpha = meth_tag, group = method )) + geom_bar(stat = "identity",position = "fill", color = "black") + theme_bw() + theme(axis.text.x = element_text(size = 7, angle = 60, hjust = 1), axis.title = element_text(size = 12, face = "bold")) + scale_fill_manual(values =c("#E6550D","#756BB1","#31A354"))  + scale_y_continuous(expand = expansion(mult = c(0, 0.1)),labels=scales::percent) + scale_alpha_manual(values=c(seq(0.1,1, length.out = 10)))+ labs(x = "method", y = "% CpGs",fill = "method", alpha = "% methylation") +  geom_text(aes(y=cumsum, label=label), vjust=-0.5, size = 2.5) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank()) + facet_grid(~ group_simp, space="free_x", scales="free_x") + theme(strip.background = element_rect(fill=NA,colour="grey50"),panel.spacing=unit(0,"cm"))
#dev.off()

#RRBS zoomed

Mcap_cov_perc_STACKED_rrbsZOOM <- Mcap_cov_perc_STACKED[which(Mcap_cov_perc_STACKED$meth_tag!="[0-10%]" & Mcap_cov_perc_STACKED$meth_tag!="[10-20%]" & Mcap_cov_perc_STACKED$method=="RRBS" & Mcap_cov_perc_STACKED$group_simp!="MBD, RRBS" & Mcap_cov_perc_STACKED$group_simp!="MBD, WGBS"),]

Mcap_cov_perc_STACKED_rrbsZOOM <- data.frame(Mcap_cov_perc_STACKED_rrbsZOOM) %>% group_by(group_simp, method) %>%  mutate(label = ifelse(meth_tag=="[90-100%]",paste0("N=", sum(count_meth)),""), cumsum = cumsum(perc_CpG)*100)

h <- ggplot(Mcap_cov_perc_STACKED_rrbsZOOM,aes(x = method, y = perc_CpG*100, fill = as.factor(method), alpha = meth_tag, group = method )) + geom_bar(stat = "identity",position = "stack", color = "black") + theme_bw() + theme(axis.text.x = element_text(size = 7, angle = 60, hjust = 1), axis.title = element_text(size = 12, face = "bold")) + scale_fill_manual(values =c("#756BB1"))  + scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + scale_alpha_manual(values=c(seq(0.3,1, length.out = 8)))+ labs(x = "method", y = "% CpGs",fill = "method", alpha = "% methylation") + guides(fill=guide_legend(reverse=T)) + geom_text(aes(y=cumsum * 1.05, label=label), size = 2.5) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank()) + facet_wrap(~group_simp, scale="free") + theme(strip.background = element_rect(fill=NA,colour="grey50"))

#wgbs zoomed
Mcap_cov_perc_STACKED_wgbsZOOM <- Mcap_cov_perc_STACKED[which(Mcap_cov_perc_STACKED$meth_tag!="[0-10%]" & Mcap_cov_perc_STACKED$meth_tag!="[10-20%]" & Mcap_cov_perc_STACKED$method=="WGBS" & Mcap_cov_perc_STACKED$group_simp!="MBD, RRBS" & Mcap_cov_perc_STACKED$group_simp!="MBD, WGBS"),]

Mcap_cov_perc_STACKED_wgbsZOOM <- data.frame(Mcap_cov_perc_STACKED_wgbsZOOM) %>% group_by(group_simp, method) %>%  mutate(label = ifelse(meth_tag=="[90-100%]",paste0("N=", sum(count_meth)),""), cumsum = cumsum(perc_CpG)*100)



i <- ggplot(Mcap_cov_perc_STACKED_wgbsZOOM,aes(x = method, y = perc_CpG*100, fill = as.factor(method), alpha = meth_tag, group = method )) + geom_bar(stat = "identity",position = "stack", color = "black") + theme_bw() + theme(axis.text.x = element_text(size = 7, angle = 60, hjust = 1), axis.title = element_text(size = 12, face = "bold")) + scale_fill_manual(values =c("#31A354"))  + scale_y_continuous(expand = expansion(mult = c(0, 0.1))) + scale_alpha_manual(values=c(seq(0.3,1, length.out = 8)))+ labs(x = "method", y = "% CpGs",fill = "method", alpha = "% methylation") + guides(fill=guide_legend(reverse=T)) + geom_text(aes(y=cumsum * 1.05, label=label), size = 2.5) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank()) + facet_wrap(~group_simp, scale="free") + theme(strip.background = element_rect(fill=NA,colour="grey50"))



jpeg("OLD_Output/Mcap_Pact_5xCpGmeth_overlapMethods_StackedBars_colbyMethod_3x_multi.jpg", width = 10, height = 12, units = "in", res = 300)
ggarrange(
  g,                # First row with line plot
  # Second row with box and dot plots
  ggarrange(h, i, ncol = 2, labels = c("B", "C"),legend = "none"), 
  ggarrange(d, ncol = 1, labels = "D", legend = "none"),
  ggarrange(e, f, ncol = 2, labels = c("E", "F"),legend = "none"), 
  nrow = 4, 
  labels = "A",       # Label of the line plot
  common.legend = TRUE, heights = c(1.5,1)
  ) 
dev.off()
```
