---
title: "heatscatter"
author: "HM Putnam"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

load libraries
```{r}
library(ggplot2)
library(tidyverse)
library(RColorBrewer)
library(wesanderson)
library(stats)
library(gridExtra)
library(psych)
library(colorRamps)

```

add border color to histogram
```{r}
#trace(pairs.panels, edit = T)

# add border argument to "panel.hist.density" code

  #rect(breaks - interbreak, 0, breaks + interbreak, 
  #               y, col = hist.col, border = "black")

#add colramp argument to "panel.smoother" code
  # if (smoother) {
#              smoothScatter(x, y, add = TRUE, nrpoints = 0, colramp = colorRampPalette(colorRamps::matlab.like2(10)))
         }

```

correlation of common loci
```{r}

#load corr data
mcap.corrs <- read.table("OLD_Output/Mcap_union5xCpG_PCAinput.tsv")
pact.corrs <- read.table("OLD_Output/Pact_union5xCpG_PCAinput.tsv")

#order colums the same
mcap.corrs <- mcap.corrs[,order(colnames(mcap.corrs))]
pact.corrs <- pact.corrs[,order(colnames(pact.corrs))]

#create one pdf file that plots will be saved in
#pdf('OLD_Output/corrplot1.pdf', width=10, height=10)
#format the plot axis size
par(mfrow =c(2,1),cex.axis = 1.5)

#create corr plot for Mcap
#pairs.panels(mcap.corrs, smooth=TRUE, scale=TRUE, cex.cor = 3, density=FALSE, show.points=FALSE, ellipses=FALSE,smoother=TRUE, gap=0.5, hist.col="gray80", breaks = 20)

#create corr plot for Pact
#pairs.panels(pact.corrs, smooth=TRUE, scale=TRUE, cex.cor = 3, density=FALSE, show.points=FALSE, ellipses=FALSE, smoother=TRUE, gap=0.5, hist.col="gray80", breaks = 20)

#save all plots in PDF
#dev.off()


#create separate PDFs for each plot

#Attempt to add legend to corrplot
#jpeg('output/intermediate-files/CorrPlots_CommonDataset/corrplot_Mcap_test.jpg', width=10, height=10, units = "in", res = 300)
#format the plot axis size
#oldmar <- par()$mar
#par(cex.axis = 1.5,mar=c(5.1,3.1,4.1,4.1))
#par(cex.axis = 1.5)
#create corr plot for Mcap
#pairs.panels(mcap.corrs, smooth=TRUE, scale=FALSE, density=FALSE, show.points=FALSE, ellipses=FALSE,smoother=TRUE, gap=0.5, hist.col="gray80", breaks = 20)
#gradientLegend(valRange=c(0,1), n.seg = c(0.25,0.5,0.75),pos=.5,side=4, color=colorRamps::matlab.like2(10))
#par(mar=oldmar) # return old values
#dev.off()

#this didn't work so I just made the legend and added it in ppt
jpeg('output/intermediate-files/CorrPlots_CommonDataset/legend.jpg', width=6, height=5, units = "in", res = 300)
par(cex.axis = 1.5,mar=c(5.1,3.1,4.1,10))
emptyPlot(1,1, main='Test plot')
gradientLegend(valRange=c(0,1), n.seg = c(0.25,0.5,0.75),pos=.5,side=4, color=colorRamps::matlab.like2(10))
dev.off()


#create corr plot for Mcap
jpeg('output/intermediate-files/CorrPlots_CommonDataset/corrplot_Mcap.jpg', width=10, height=10, units = "in", res = 300)
#format the PDF
par(cex.axis = 1.5)
pairs.panels(mcap.corrs, smooth=TRUE, scale=FALSE, density=FALSE, show.points=FALSE, ellipses=FALSE, smoother=TRUE, gap=0.5, hist.col="gray80", breaks = 20)
dev.off()


#create corr plot for Pact
jpeg('output/intermediate-files/CorrPlots_CommonDataset/corrplot_Pact.jpg', width=10, height=10, units = "in", res = 300)
#format the PDF
par(cex.axis = 1.5)
pairs.panels(pact.corrs, smooth=TRUE, scale=FALSE, density=FALSE, show.points=FALSE, ellipses=FALSE, smoother=TRUE, gap=0.5, hist.col="gray80", breaks = 20)
dev.off()




```

Save plots in 'output' dir
```{r}
#create corr plot for Mcap
a <- pairs.panels(mcap.corrs, smooth=TRUE, scale=TRUE, cex.cor = 3, density=FALSE, show.points=FALSE, ellipses=FALSE,smoother=TRUE, gap=0.5, hist.col="gray80", breaks = 20)

#create corr plot for Pact
b <- pairs.panels(pact.corrs, smooth=TRUE, scale=TRUE, cex.cor = 3, density=FALSE, show.points=FALSE, ellipses=FALSE, smoother=TRUE, gap=0.5, hist.col="gray80", breaks = 20)

jpeg("output/figures/Fig_6.jpg", width = 5, height = 10, units = "in", res = 300)
ggarrange(a,b,nrow = 2,labels = "AUTO")
dev.off()



```


```{r}
mcap.corrs_w1_w2 <- mcap.corrs[,c(1,2)]
mcap.corrs_w1_w3 <- mcap.corrs[,c(1,3)]
mcap.corrs_w2_w3 <- mcap.corrs[,c(2,3)]


k <- 11
my.cols <- wes_palette("Zissou1", 100, type = "continuous")
pdf('OLD_Output/corrplot2.pdf', width=10, height=10)
par(mfrow=c(2,2))
smoothScatter(mcap.corrs1, nrpoints = Inf, colramp=colorRampPalette(my.cols), pch=16, cex=.1)
smoothScatter(mcap.corrs3, nrpoints = Inf, colramp=colorRampPalette(my.cols), pch=16, cex=.1)
smoothScatter(mcap.corrs2, nrpoints = Inf, colramp=colorRampPalette(my.cols), pch=16, cex=.1)
smoothScatter(mcap.corrs3, nrpoints = Inf, colramp=colorRampPalette(my.cols), pch=16, cex=.1)
dev.off()
# 

```