---
title: "Untitled"
author: "Shelly Trigg"
date: "5/14/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

load libraries
```{r}
library(data.table)
library(ggplot2)
library(dplyr)

```

read in data
```{r}
#data for percent genome coverage
#these were generated by https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/20200416_CollectWgsMetrics.sh 

Meth1 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth1_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth2 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth2_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth3 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth3_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth4 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth4_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")

Meth5 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth5_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")

Meth6 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth6_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")

Meth7 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth7_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth8 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth8_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth9 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Pact/Meth9_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

#Mcap
Meth10 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth10_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth11 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth11_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth12 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth12_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth13 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth13_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")

Meth14 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth14_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")

Meth15 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth15_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")

Meth16 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth16_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth17 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth17_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Meth18 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200416/Mcap/Meth18_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")



# data for saturation estimates
#these data were generated by https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200513_SubsamplePicardPact.sh and https://gannet.fish.washington.edu/metacarcinus/mox_jobs/20200527_SubsamplePicardMcap.sh

Pact_WGBS_50 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_WGBS_50M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Pact_WGBS_100 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_WGBS_100M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Pact_WGBS_150 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_WGBS_150M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Pact_WGBS_200 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_WGBS_200M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Pact_RRBS_50 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_RRBS_50M_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")
Pact_RRBS_100 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_RRBS_100M_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")
Pact_RRBS_150 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_RRBS_150M_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")
Pact_RRBS_200 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_RRBS_200M_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")

Pact_MBD_50 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_MBD_50M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Pact_MBD_100 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_MBD_100M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Pact_MBD_150 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_MBD_150M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Pact_MBD_200 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200513/Pact_MBD_200M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")


#Mcap
Mcap_WGBS_50 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_WGBS_50M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Mcap_WGBS_100 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_WGBS_100M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Mcap_WGBS_150 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_WGBS_150M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Mcap_WGBS_200 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_WGBS_200M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

Mcap_RRBS_50 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_RRBS_50M_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")
Mcap_RRBS_100 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_RRBS_100M_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")
Mcap_RRBS_150 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_RRBS_150M_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")
Mcap_RRBS_200 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_RRBS_200M_R1_001_val_1_bismark_bt2_pe.collect_wgs_metrics.txt")

Mcap_MBD_50 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_MBD_50M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Mcap_MBD_100 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_MBD_100M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Mcap_MBD_150 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_MBD_150M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")
Mcap_MBD_200 <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_MBD_200M_R1_001_val_1_bismark_bt2_pe.deduplicated.collect_wgs_metrics.txt")

#CpG data for samples and for pooled samples
#These data were generated by https://github.com/hputnam/Meth_Compare/blob/master/scripts/Pact_CpG_coverageXdepth.ipynb and https://github.com/hputnam/Meth_Compare/blob/master/scripts/Mcap_CpG_coverageXdepth.ipynb . The CSV files were created from copying and pasting numbers from jupyter output.

Pact_Sample_CpG <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200514/Pact_CpG_coverage.csv")

Pact_pool_Sample_CpG <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200514/Pact_CpG_est_coverage.csv")

#Mcap 

Mcap_Sample_CpG <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_CpG_coverage.csv")

Mcap_pool_Sample_CpG <- fread("https://gannet.fish.washington.edu/metacarcinus/FROGER_meth_compare/20200527/Mcap_CpG_est_coverage.csv")

```

Add meta data 
```{r}
#data for percent genome coverage
# add method column
Meth1$method <- "WGBS"
Meth2$method <- "WGBS"
Meth3$method <- "WGBS"
Meth4$method <- "RRBS"
Meth5$method <- "RRBS"
Meth6$method <- "RRBS"
Meth7$method <- "MBD"
Meth8$method <- "MBD"
Meth9$method <- "MBD"

Meth10$method <- "WGBS"
Meth11$method <- "WGBS"
Meth12$method <- "WGBS"
Meth13$method <- "RRBS"
Meth14$method <- "RRBS"
Meth15$method <- "RRBS"
Meth16$method <- "MBD"
Meth17$method <- "MBD"
Meth18$method <- "MBD"

# data for saturation estimates
#add group and depth info to each dataframe

#pact 

Pact_WGBS_50$method <- "WGBS"
Pact_WGBS_50$depth <- "50"

Pact_WGBS_100$method <- "WGBS"
Pact_WGBS_100$depth <- "100"

Pact_WGBS_150$method <- "WGBS"
Pact_WGBS_150$depth <- "150"

Pact_WGBS_200$method <- "WGBS"
Pact_WGBS_200$depth <- "200"

Pact_RRBS_50$method <- "RRBS"
Pact_RRBS_50$depth <- "50"

Pact_RRBS_100$method <- "RRBS"
Pact_RRBS_100$depth <- "100"

Pact_RRBS_150$method <- "RRBS"
Pact_RRBS_150$depth <- "150"

Pact_RRBS_200$method <- "RRBS"
Pact_RRBS_200$depth <- "200"

Pact_MBD_50$method <- "MBD"
Pact_MBD_50$depth <- "50"

Pact_MBD_100$method <- "MBD"
Pact_MBD_100$depth <- "100"

Pact_MBD_150$method <- "MBD"
Pact_MBD_150$depth <- "150"

Pact_MBD_200$method <- "MBD"
Pact_MBD_200$depth <- "200"

#Mcap

Mcap_WGBS_50$method <- "WGBS"
Mcap_WGBS_50$depth <- "50"

Mcap_WGBS_100$method <- "WGBS"
Mcap_WGBS_100$depth <- "100"

Mcap_WGBS_150$method <- "WGBS"
Mcap_WGBS_150$depth <- "150"

Mcap_WGBS_200$method <- "WGBS"
Mcap_WGBS_200$depth <- "200"

Mcap_RRBS_50$method <- "RRBS"
Mcap_RRBS_50$depth <- "50"

Mcap_RRBS_100$method <- "RRBS"
Mcap_RRBS_100$depth <- "100"

Mcap_RRBS_150$method <- "RRBS"
Mcap_RRBS_150$depth <- "150"

Mcap_RRBS_200$method <- "RRBS"
Mcap_RRBS_200$depth <- "200"

Mcap_MBD_50$method <- "MBD"
Mcap_MBD_50$depth <- "50"

Mcap_MBD_100$method <- "MBD"
Mcap_MBD_100$depth <- "100"

Mcap_MBD_150$method <- "MBD"
Mcap_MBD_150$depth <- "150"

Mcap_MBD_200$method <- "MBD"
Mcap_MBD_200$depth <- "200"


# CpG data for samples
# add method column

#Pact

for(i in 1:nrow(Pact_Sample_CpG)){
  if(Pact_Sample_CpG$Sample[i] == "Meth_1" |Pact_Sample_CpG$Sample[i] == "Meth_2" | Pact_Sample_CpG$Sample[i] == "Meth_3"){
    Pact_Sample_CpG$method[i] <- "WGBS"
  }
  if(Pact_Sample_CpG$Sample[i] == "Meth_4" |Pact_Sample_CpG$Sample[i] == "Meth_5" | Pact_Sample_CpG$Sample[i] == "Meth_6"){
    Pact_Sample_CpG$method[i] <- "RRBS"
  }
  if(Pact_Sample_CpG$Sample[i] == "Meth_7" |Pact_Sample_CpG$Sample[i] == "Meth_8" | Pact_Sample_CpG$Sample[i] == "Meth_9"){
    Pact_Sample_CpG$method[i] <- "MBD"
  }
}

#Mcap
for(i in 1:nrow(Mcap_Sample_CpG)){
  if(Mcap_Sample_CpG$Sample[i] == "Meth_10" |Mcap_Sample_CpG$Sample[i] == "Meth_11" | Mcap_Sample_CpG$Sample[i] == "Meth_12"){
    Mcap_Sample_CpG$method[i] <- "WGBS"
  }
  if(Mcap_Sample_CpG$Sample[i] == "Meth_13" |Mcap_Sample_CpG$Sample[i] == "Meth_14" | Mcap_Sample_CpG$Sample[i] == "Meth_15"){
    Mcap_Sample_CpG$method[i] <- "RRBS"
  }
  if(Mcap_Sample_CpG$Sample[i] == "Meth_16" |Mcap_Sample_CpG$Sample[i] == "Meth_17" | Mcap_Sample_CpG$Sample[i] == "Meth_18"){
    Mcap_Sample_CpG$method[i] <- "MBD"
  }
}
```

combine sample data frames
```{r}
#data for percent genome coverage
Pact_samples <- rbind(Meth1,Meth2, Meth3, Meth4, Meth5, Meth6, Meth7, Meth8, Meth9)

Mcap_samples <- rbind(Meth10,Meth11, Meth12, Meth13, Meth14, Meth15, Meth16, Meth17, Meth18)

# data for saturation estimates

Pact_all <- rbind(Pact_WGBS_50, Pact_WGBS_100, Pact_WGBS_150, Pact_WGBS_200, Pact_RRBS_50, Pact_RRBS_100, Pact_RRBS_150, Pact_RRBS_200, Pact_MBD_50, Pact_MBD_100, Pact_MBD_150, Pact_MBD_200)

Mcap_all <- rbind(Mcap_WGBS_50, Mcap_WGBS_100, Mcap_WGBS_150, Mcap_WGBS_200, Mcap_RRBS_50, Mcap_RRBS_100, Mcap_RRBS_150, Mcap_RRBS_200, Mcap_MBD_50, Mcap_MBD_100, Mcap_MBD_150, Mcap_MBD_200)

```

format for plotting
```{r}
#data for percent genome coverage
#reformat to long
Pact_samples_stacked <- tidyr::gather(Pact_samples, "coverage", "percent_genome", 13:26)
#remove PCT_ from coverage column
Pact_samples_stacked$coverage <- gsub("PCT_","", Pact_samples_stacked$coverage)
#remove X from coverage column
Pact_samples_stacked$coverage <- gsub("X","", Pact_samples_stacked$coverage)
#make coverage a numeric class
Pact_samples_stacked$coverage <- as.numeric(Pact_samples_stacked$coverage)



# data for saturation estimates
#reformat to long
Pact_all_stacked <- tidyr::gather(Pact_all, "coverage", "percent_genome", 13:26)
#remove PCT_ from coverage column
Pact_all_stacked$coverage <- gsub("PCT_","", Pact_all_stacked$coverage)
#remove X from coverage column
Pact_all_stacked$coverage <- gsub("X","", Pact_all_stacked$coverage)
#make coverage a numeric class
Pact_all_stacked$coverage <- as.numeric(Pact_all_stacked$coverage)
#reorder depth column and change to class factor for plotting
Pact_all_stacked$depth <- factor(Pact_all_stacked$depth, levels = c("200", "150", "100", "50"))

#CpG sample data
#reformat to long
Pact_Sample_CpG_stacked <- tidyr::gather(Pact_Sample_CpG, "coverage", "percent_CpG", 2:15)
#remove X from coverage column
Pact_Sample_CpG_stacked$coverage <- gsub("x","", Pact_Sample_CpG_stacked$coverage)
#make coverage a numeric class
Pact_Sample_CpG_stacked$coverage <- as.numeric(Pact_Sample_CpG_stacked$coverage)
#calculate percent CpG by dividing number of CpG by total number CpG in genome (9155620)
Pact_Sample_CpG_stacked$percent_CpG <- (Pact_Sample_CpG_stacked$percent_CpG/9155620)
#convert MBD to MBDBS
Pact_Sample_CpG_stacked$method <- gsub("MBD", "MBDBS", Pact_Sample_CpG_stacked$method)

#CpGs for pooled sample data
#reformat to long
Pact_pool_Sample_CpG_stacked <-  tidyr::gather(Pact_pool_Sample_CpG, "coverage", "percent_CpG", 3:16)
#remove X from coverage column
Pact_pool_Sample_CpG_stacked$coverage <- gsub("x","", Pact_pool_Sample_CpG_stacked$coverage)
#make coverage a numeric class
Pact_pool_Sample_CpG_stacked$coverage <- as.numeric(Pact_pool_Sample_CpG_stacked$coverage)
#calculate percent CpG by dividing number of CpG by total number CpG in genome (9155620)
Pact_pool_Sample_CpG_stacked$percent_CpG <- (Pact_pool_Sample_CpG_stacked$percent_CpG/9155620)
#reorder depth column and change to class factor for plotting
Pact_pool_Sample_CpG_stacked$depth <- factor(Pact_pool_Sample_CpG_stacked$depth, levels = c("200", "150", "100", "50"))
#convert MBD to MBDBS
Pact_pool_Sample_CpG_stacked$method <- gsub("MBD", "MBDBS", Pact_pool_Sample_CpG_stacked$method)

#Mcap

#data for percent genome coverage
#reformat to long
Mcap_samples_stacked <- tidyr::gather(Mcap_samples, "coverage", "percent_genome", 13:26)
#remove PCT_ from coverage column
Mcap_samples_stacked$coverage <- gsub("PCT_","", Mcap_samples_stacked$coverage)
#remove X from coverage column
Mcap_samples_stacked$coverage <- gsub("X","", Mcap_samples_stacked$coverage)
#make coverage a numeric class
Mcap_samples_stacked$coverage <- as.numeric(Mcap_samples_stacked$coverage)



# data for saturation estimates
#reformat to long
Mcap_all_stacked <- tidyr::gather(Mcap_all, "coverage", "percent_genome", 13:26)
#remove PCT_ from coverage column
Mcap_all_stacked$coverage <- gsub("PCT_","", Mcap_all_stacked$coverage)
#remove X from coverage column
Mcap_all_stacked$coverage <- gsub("X","", Mcap_all_stacked$coverage)
#make coverage a numeric class
Mcap_all_stacked$coverage <- as.numeric(Mcap_all_stacked$coverage)
#reorder depth column and change to class factor for plotting
Mcap_all_stacked$depth <- factor(Mcap_all_stacked$depth, levels = c("200", "150", "100", "50"))

#CpG sample data
#reformat to long
Mcap_Sample_CpG_stacked <- tidyr::gather(Mcap_Sample_CpG, "coverage", "percent_CpG", 2:15)
#remove X from coverage column
Mcap_Sample_CpG_stacked$coverage <- gsub("x","", Mcap_Sample_CpG_stacked$coverage)
#make coverage a numeric class
Mcap_Sample_CpG_stacked$coverage <- as.numeric(Mcap_Sample_CpG_stacked$coverage)
#calculate percent CpG by dividing number of CpG by total number CpG in genome (9155620)
Mcap_Sample_CpG_stacked$percent_CpG <- (Mcap_Sample_CpG_stacked$percent_CpG/28684519)
#convert MBD to MBDBS
Mcap_Sample_CpG_stacked$method <- gsub("MBD", "MBDBS", Mcap_Sample_CpG_stacked$method)


#CpGs for pooled sample data
#reformat to long
Mcap_pool_Sample_CpG_stacked <-  tidyr::gather(Mcap_pool_Sample_CpG, "coverage", "percent_CpG", 3:16)
#remove X from coverage column
Mcap_pool_Sample_CpG_stacked$coverage <- gsub("x","", Mcap_pool_Sample_CpG_stacked$coverage)
#make coverage a numeric class
Mcap_pool_Sample_CpG_stacked$coverage <- as.numeric(Mcap_pool_Sample_CpG_stacked$coverage)
#calculate percent CpG by dividing number of CpG by total number CpG in genome (9155620)
Mcap_pool_Sample_CpG_stacked$percent_CpG <- (Mcap_pool_Sample_CpG_stacked$percent_CpG/28684519)
#reorder depth column and change to class factor for plotting
Mcap_pool_Sample_CpG_stacked$depth <- factor(Mcap_pool_Sample_CpG_stacked$depth, levels = c("200", "150", "100", "50"))
#convert MBD to MBDBS
Mcap_pool_Sample_CpG_stacked$method <- gsub("MBD", "MBDBS", Mcap_pool_Sample_CpG_stacked$method)
```

plot coverage
```{r}
# fraction of genome covered x method
jpeg("../../Output/Pact_GenomecovXmethod_sample_avg.jpg", width = 4.5, height = 3, units = "in", res = 300)
ggplot(Pact_samples_stacked[which(Pact_samples_stacked$coverage <= 50),], aes(x = coverage, y = percent_genome, color = method)) + geom_smooth(aes(fill = method)) + scale_x_continuous(breaks = seq(0,100,10)) + scale_fill_manual(values = c("#E6550D", "#756BB1","#31A354")) + scale_color_manual(values = c("#E6550D", "#756BB1","#31A354" )) + xlab("coverage (X)") + ylab("fraction of genome") + theme_bw() + theme(text = element_text(size=16))
dev.off()

#fraction of CpGs covered x method
jpeg("../../Output/Pact_CpGcovXmethod_sample_avg.jpg", width = 4.5, height = 3, units = "in", res = 300)
ggplot(Pact_Sample_CpG_stacked[which(Pact_Sample_CpG_stacked$coverage <= 50),], aes(x = coverage, y = percent_CpG, color = method)) + geom_smooth(aes(fill = method)) + scale_x_continuous(breaks = seq(0,100,10)) + scale_fill_manual(values = c("#E6550D", "#756BB1","#31A354")) + scale_color_manual(values = c("#E6550D", "#756BB1","#31A354" )) + xlab("coverage (X)") + ylab("fraction of CpGs") + theme_bw() + theme(text = element_text(size=16))
dev.off()

# fraction of genome covered by pooled samples
jpeg("../../Output/Pact_GenomecovXmethod_pooled_subsamples.jpg", width = 9, height = 3, units = "in", res = 300)
ggplot(Pact_all_stacked[which(Pact_all_stacked$coverage<=50),], aes(x = coverage, y= percent_genome, group = paste(method, depth, sep = "_"),color = depth)) + geom_line(size = 1, alpha = 0.8) + facet_wrap(~method)+  scale_x_continuous(breaks = seq(0,100,10))+ xlab("coverage (X)") + ylab("fraction of genome") + labs(color = "depth (M reads)") + scale_color_grey() + theme_bw() + theme(text = element_text(size=16)) + theme(strip.background =element_rect(fill="white"))
dev.off()

# fraction of CpGs covered by pooled samples

jpeg("../../Output/Pact_CpGcovXmethod_pooled_subsamples.jpg", width = 9, height = 3, units = "in", res = 300)
ggplot(Pact_pool_Sample_CpG_stacked[which(Pact_pool_Sample_CpG_stacked$coverage<=50),], aes(x = coverage, y= percent_CpG, group = paste(method, depth, sep = "_"),color = depth)) + geom_line(size = 1, alpha = 0.8) + facet_wrap(~method)+  scale_x_continuous(breaks = seq(0,100,10))+ xlab("coverage (X)") + ylab("fraction of CpGs") + labs(color = "depth (M reads)") + scale_color_grey() + theme_bw() + theme(text = element_text(size=16)) + theme(strip.background =element_rect(fill="white"))
dev.off()

#Mcap

# fraction of genome covered x method
jpeg("../../Output/Mcap_GenomecovXmethod_sample_avg.jpg", width = 4.5, height = 3, units = "in", res = 300)
ggplot(Mcap_samples_stacked[which(Mcap_samples_stacked$coverage <= 50),], aes(x = coverage, y = percent_genome, color = method)) + geom_smooth(aes(fill = method)) + scale_x_continuous(breaks = seq(0,100,10)) + scale_fill_manual(values = c("#E6550D", "#756BB1","#31A354")) + scale_color_manual(values = c("#E6550D", "#756BB1","#31A354" )) + xlab("coverage (X)") + ylab("fraction of genome") + theme_bw() + theme(text = element_text(size=16))
dev.off()

#fraction of CpGs covered x method
jpeg("../../Output/Mcap_CpGcovXmethod_sample_avg.jpg", width = 4.5, height = 3, units = "in", res = 300)
ggplot(Mcap_Sample_CpG_stacked[which(Mcap_Sample_CpG_stacked$coverage <= 50),], aes(x = coverage, y = percent_CpG, color = method)) + geom_smooth(aes(fill = method)) + scale_x_continuous(breaks = seq(0,100,10)) + scale_fill_manual(values = c("#E6550D", "#756BB1","#31A354")) + scale_color_manual(values = c("#E6550D", "#756BB1","#31A354" )) + xlab("coverage (X)") + ylab("fraction of CpGs") + theme_bw() + theme(text = element_text(size=16))
dev.off()

# fraction of genome covered by pooled samples
jpeg("../../Output/Mcap_GenomecovXmethod_pooled_subsamples.jpg", width = 9, height = 3, units = "in", res = 300)
ggplot(Mcap_all_stacked[which(Mcap_all_stacked$coverage<=50),], aes(x = coverage, y= percent_genome, group = paste(method, depth, sep = "_"),color = depth)) + geom_line(size = 1, alpha = 0.8) + facet_wrap(~method)+  scale_x_continuous(breaks = seq(0,100,10))+ xlab("coverage (X)") + ylab("fraction of genome") + labs(color = "depth (M reads)") + scale_color_grey() + theme_bw() + theme(text = element_text(size=16)) + theme(strip.background =element_rect(fill="white"))
dev.off()

# fraction of CpGs covered by pooled samples

jpeg("../../Output/Mcap_CpGcovXmethod_pooled_subsamples.jpg", width = 9, height = 3, units = "in", res = 300)
ggplot(Mcap_pool_Sample_CpG_stacked[which(Mcap_pool_Sample_CpG_stacked$coverage<=50),], aes(x = coverage, y= percent_CpG, group = paste(method, depth, sep = "_"),color = depth)) + geom_line(size = 1, alpha = 0.8) + facet_wrap(~method)+  scale_x_continuous(breaks = seq(0,100,10))+ xlab("coverage (X)") + ylab("fraction of CpGs") + labs(color = "depth (M reads)") + scale_color_grey() + theme_bw() + theme(text = element_text(size=16)) + theme(strip.background =element_rect(fill="white"))
dev.off()
```

