---
title: "Circos Meth Compare"
author: "HM Putnam"
date: "7/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Libraries
```{r}
library(circlize) 
library(tidyverse)
library(ComplexHeatmap)
```

Generate Circos plots
#https://jokergoo.github.io/circlize_book/book/initialize-genomic-plot.html#customize-chromosome-track
#The input data for circos.genomicInitialize() is also a data frame with at least three columns. The first column is genomic category (for cytoband data, it is chromosome name), and the next two columns are positions in each genomic category.

Montipora capitata
```{r}
#read in the 5x coverage bedgraph of CpG for all 9 samples, 3 reps x 3 methods 
Mcap <- read.table("../data/Mcap_union_5x.bedgraph", sep = "\t", header = TRUE, stringsAsFactors = FALSE)
head(Mcap)
str(Mcap)

#load in all genes gff from a genome
Mcap.cytoband <- read.table("../genome-feature-files/Mcap.GFFannotation.genes.gff", sep = "\t",  
                            header = FALSE)

#remove extra coloumns from gene gff
Mcap.cytoband.df <- Mcap.cytoband[,c(1,4,5,6,9)]
str(Mcap.cytoband.df)
head(Mcap.cytoband.df)

n_distinct(Mcap.cytoband$V1)

Mcap.gene.cytoband <- Mcap.cytoband[,c(1,4,5,6,7)]
Mcap.gene.cytoband$V4 <-as.numeric(Mcap.gene.cytoband$V4)
Mcap.gene.cytoband$V5 <- as.numeric(Mcap.gene.cytoband$V5)
Mcap.gene.cytoband$V6 <- as.numeric(0.5)
Mcap.gene.cytoband$V7 <- as.numeric(1.0)
Mcap.gene.cytoband <- Mcap.gene.cytoband %>%
  filter(V1 == 2 )

#examine scaffolds for the number of genes in a scaffold 
Mcap.sizes <- Mcap.cytoband %>% 
  group_by(V1) %>% 
  summarise(count=n()) %>%
  arrange(-count)


Mcap.cytoband.df <- Mcap.cytoband.df %>%
  filter(V1 == 2 )

Mcap_union <- Mcap %>%
  filter(chrom== 2)

#set all CpG data as numeric
Mcap_union$X10 <-as.numeric(Mcap_union$X10)
Mcap_union$X11 <-as.numeric(Mcap_union$X11)
Mcap_union$X12 <-as.numeric(Mcap_union$X12)
Mcap_union$X13 <-as.numeric(Mcap_union$X13)
Mcap_union$X14 <-as.numeric(Mcap_union$X14)
Mcap_union$X15 <-as.numeric(Mcap_union$X15)
Mcap_union$X16 <-as.numeric(Mcap_union$X16)
Mcap_union$X17 <-as.numeric(Mcap_union$X17)
Mcap_union$X18 <-as.numeric(Mcap_union$X18)

#scale the data from 0-1
Mcap_union.WGBS <- Mcap_union %>% mutate(avg = rowMeans(.[4:6], na.rm=TRUE))
Mcap_union.WGBS <- Mcap_union.WGBS[,c(1,2,3,13)]
Mcap_union.WGBS$avg <- Mcap_union.WGBS$avg/100
Mcap_union.RRBS <- Mcap_union %>% mutate(avg = rowMeans(.[7:9], na.rm=TRUE))
Mcap_union.RRBS <- Mcap_union.RRBS[,c(1,2,3,13)]
Mcap_union.RRBS$avg <- Mcap_union.RRBS$avg/100
Mcap_union.MBDBS <- Mcap_union %>% mutate(avg = rowMeans(.[10:12], na.rm=TRUE))
Mcap_union.MBDBS <- Mcap_union.MBDBS[,c(1,2,3,13)]
Mcap_union.MBDBS$avg <- Mcap_union.MBDBS$avg/100

#plot top 5 scaffolds with the greatest number of gene
pdf('../Output/Mcap_genes_CpG_3methods_top5.pdf')
circos.clear()

#circos.initializeWithIdeogram(Mcap.cytoband.df, species = NULL, sort.chr = TRUE)
circos.initializeWithIdeogram(Mcap.gene.cytoband, species = NULL, sort.chr = TRUE)
circos.genomicTrack(Mcap_union.WGBS, stack=FALSE, ylim=c(0,1), track.height = 0.1,
                    panel.fun = function(region, value, ...) {
                      circos.genomicPoints(region, value, pch = 16, cex = 0.2, col="#31A354")
                    })

circos.genomicTrack(Mcap_union.RRBS, stack=FALSE, ylim=c(0,1),track.height = 0.1,
                    panel.fun = function(region, value, ...) {
                      circos.genomicPoints(region, value, pch = 16, cex = 0.2, col="#756BB1")
                    })

circos.genomicTrack(Mcap_union.MBDBS, stack=FALSE, ylim=c(0,1), track.height = 0.1,
                    panel.fun = function(region, value, ...) {
                      circos.genomicPoints(region, value, pch = 16, cex = 0.2, col="#E6550D")
                    })
dev.off()

```

Pocillopora acuta
```{r}
#read in the 5x coverage bedgraph of CpG for all 9 samples, 3 reps x 3 methods 
Pact <- read.table("../data/Pact_union_5x.bedgraph", sep = "\t", header = TRUE, stringsAsFactors = FALSE)
head(Pact)
str(Pact)

#load in all genes gff from a genome
Pact.cytoband <- read.table("../genome-feature-files/Pact.GFFannotation.genes.gff", sep = "\t",  
                       header = FALSE,colClasses = c("character","character","character", "numeric",
                       "numeric",  "numeric", "character", "character", "character") )

#remove extra coloumns from gene gff
Pact.cytoband.df <- Pact.cytoband[,c(1,4,5,6,9)]
str(Pact.cytoband.df)
head(Pact.cytoband.df)

n_distinct(Pact.cytoband$V1)

Pact.gene.cytoband <- Pact.cytoband[,c(1,4,5,6,7)]
Pact.gene.cytoband$V4 <-as.numeric(Pact.gene.cytoband$V4)
Pact.gene.cytoband$V5 <- as.numeric(Pact.gene.cytoband$V5)
Pact.gene.cytoband$V6 <- as.numeric(0.5)
Pact.gene.cytoband$V7 <- as.numeric(1.0)
Pact.gene.cytoband <- Pact.gene.cytoband %>%
  filter(V1 == "scaffold502_cov107" )

#examine scaffolds for the number of genes in a scaffold 
Pact.sizes <- Pact.cytoband %>% 
  group_by(V1) %>% 
  summarise(count=n()) %>%
  arrange(-count)

which(Pact.cytoband.df$V1=='scaffold502cov107')

Pact.cytoband.df <- Pact.cytoband.df %>%
  filter(V1 == "scaffold502_cov107")

Pact_union <- Pact %>%
  filter(chrom== "scaffold502_cov107")

#Pact_union$chrom <- gsub("_", "", Pact_union$chrom)

#which(Pact_union$chrom=='scaffold502_cov107')

#set all CpG data as numeric
Pact_union$X1 <-as.numeric(Pact_union$X1)
Pact_union$X2 <-as.numeric(Pact_union$X2)
Pact_union$X3 <-as.numeric(Pact_union$X3)
Pact_union$X4 <-as.numeric(Pact_union$X4)
Pact_union$X5 <-as.numeric(Pact_union$X5)
Pact_union$X6 <-as.numeric(Pact_union$X6)
Pact_union$X7 <-as.numeric(Pact_union$X7)
Pact_union$X8 <-as.numeric(Pact_union$X8)
Pact_union$X9 <-as.numeric(Pact_union$X9)

#scale the data from 0-1
Pact_union.WGBS <- Pact_union %>% mutate(avg = rowMeans(.[4:6], na.rm=TRUE))
Pact_union.WGBS <- Pact_union.WGBS[,c(1,2,3,13)]
Pact_union.WGBS$avg <- Pact_union.WGBS$avg/100
Pact_union.RRBS <- Pact_union %>% mutate(avg = rowMeans(.[7:9], na.rm=TRUE))
Pact_union.RRBS <- Pact_union.RRBS[,c(1,2,3,13)]
Pact_union.RRBS$avg <- Pact_union.RRBS$avg/100
Pact_union.MBDBS <- Pact_union %>% mutate(avg = rowMeans(.[10:12], na.rm=TRUE))
Pact_union.MBDBS <- Pact_union.MBDBS[,c(1,2,3,13)]
Pact_union.MBDBS$avg <- Pact_union.MBDBS$avg/100




#plot top 5 scaffolds with the greatest number of gene 
pdf('../Output/Pact_genes_CpG_3methods_top5.pdf')
circos.clear()

#circos.initializeWithIdeogram(Pact.cytoband.df, species = NULL, sort.chr = TRUE)
circos.initializeWithIdeogram(Pact.gene.cytoband, species = NULL, sort.chr = TRUE)
circos.genomicTrack(Pact_union.WGBS, stack=FALSE, ylim=c(0,1), track.height = 0.1,
                    panel.fun = function(region, value, ...) {
                      circos.genomicPoints(region, value, pch = 16, cex = 0.2, col="#31A354")
                    })

circos.genomicTrack(Pact_union.RRBS, stack=FALSE, ylim=c(0,1),track.height = 0.1,
                    panel.fun = function(region, value, ...) {
                      circos.genomicPoints(region, value, pch = 16, cex = 0.2, col="#756BB1")
                    })

circos.genomicTrack(Pact_union.MBDBS, stack=FALSE, ylim=c(0,1), track.height = 0.1,
                    panel.fun = function(region, value, ...) {
                      circos.genomicPoints(region, value, pch = 16, cex = 0.2, col="#E6550D")
                    })
dev.off()

```